FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

EXPOSE 4200

# --host 0.0.0.0 para que sea accesible fuera del contenedor
# --proxy-config para que /api y /keycloak pasen por el proxy sin CORS
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--proxy-config", "proxy.conf.json", "--poll", "500"]
